export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAILURE = 'USER_REGISTER_FAILURE';

export const USER_EDIT_NAME_REQUEST = 'USER_EDIT_NAME_REQUEST';
export const USER_EDIT_NAME_SUCCESS = 'USER_EDIT_NAME_SUCCESS';
export const USER_EDIT_NAME_FAILURE = 'USER_EDIT_NAME_FAILURE';
